### ISSUE TITLE
Missing AMI

### ISSUE THREAD

**Issue by dkhunt27** [mbabineau/cloudformation-mesos#6]
Looks like the AMI is missing from us-west-2...
     "us-west-2" : {
        "AMI" : "ami-db672aeb"
      },

I can see thefactory-mesos....AMIs in us-west-1 and us-east-1...but our VPC is us-west-2.  Could you please add the AMI to us-west-2?

Also, it looks like there is a newer thefactory-mesos ami in the other regions, should the references in this script be updated?

**Comment by mbabineau** [comment]
Sounds like you're working off an old revision. If you use master from https://github.com/mbabineau/cloudformation-mesos, you should be set

**Comment by dkhunt27** [comment]
That worked...thanks.  I think I might have originally forked from the mesosphere repo version
